---
# Vagrant config.
vagrant_ip: 192.168.88.88
vagrant_box: beet/dev

# Beetbox settings.
beet_project: drupal
beet_webserver: nginx
beet_domain: "beetbox.local"
beet_root: "{{ beet_base }}/projects/{{ beet_project }}"
beet_mysql_database: "beetbox_{{ beet_project }}"
beet_site_name: "Beetbox"

# Drupal settings.
drupal_create_makefile: yes
drupal_build_makefile: yes
drupal_install_site: yes
drupal_account_name: admin
drupal_account_pass: admin
php_memory_limit: "284M"

# Beetbox debug.
beet_debug: yes

# PHP config.
php_version: "7.0"

# Nginx config.
nginx_php_fpm: /var/run/php/php7.0-fpm.sock
