---
# Vagrant config.
vagrant_ip: 192.168.88.88
vagrant_box: beet/dev

# Beetbox settings.
beet_project: drupal
beet_domain: "thunder.local"
beet_root: "{{ beet_base }}/projects/thunder"
beet_site_name: "Beetbox thunder"

# Drupal settings.
drupal_build_makefile: yes
drupal_makefile_path: "{{ beet_base }}/thunder.make.yml"
drupal_install_profile: thunder
drupal_install_site: yes
drupal_account_name: admin
drupal_account_pass: admin
php_memory_limit: "284M"
