---
# Vagrant config.
vagrant_ip: 192.168.88.88
vagrant_box: beet/dev

# Beetbox settings.
beet_project: drupal
beet_domain: "govcms.local"
beet_root: "{{ beet_base }}/projects/govcms"
beet_site_name: "Beetbox"

# Drupal settings.
drupal_build_makefile: yes
drupal_makefile_path: "{{ beet_base }}/govcms.make.yml"
drupal_install_profile: govcms
drupal_install_site: yes
drupal_account_name: admin
drupal_account_pass: admin
php_memory_limit: "284M"

# Beetbox debug.
beet_debug: yes

# Install ClamAV
extra_packages:
  - clamav
  - clamav-daemon
