---
# Vagrant config.
vagrant_ip: 192.168.88.88
vagrant_box: beet/dev

# Beetbox settings.
beet_project: drupal
beet_domain: "lightning.local"
beet_root: "{{ beet_base }}/projects/lightning"
beet_site_name: "Beetbox lightning"

# Drupal settings.
drupal_build_makefile: yes
drupal_makefile_path: "{{ beet_base }}/.beetbox/lightning.make.yml"
drupal_install_profile: lightning
drupal_install_site: yes
drupal_account_name: admin
drupal_account_pass: admin

# Beetbox debug.
beet_debug: no
