---
# Vagrant config.
vagrant_ip: 192.168.88.88
vagrant_box: beet/dev

# Beetbox settings.
beet_mode: multidev
beet_project: drupal
beet_domain: "beetbox.local"
beet_root: "{{ beet_base }}/projects/{{ beet_project }}"
beet_site_name: "Beetbox"

# Drupal settings.
drupal_create_makefile: yes
drupal_build_makefile: yes
drupal_install_site: yes
drupal_account_name: admin
drupal_account_pass: admin
php_memory_limit: "284M"

# Beetbox debug.
beet_debug: no
