---
# Vagrant config.
vagrant_ip: 192.168.88.88
vagrant_box: beet/dev

# Beetbox settings.
beet_project: drupal
beet_domain: "beetbox.local"
beet_root: "{{ beet_base }}/projects/{{ beet_project }}"
beet_mysql_database: "beetbox_{{ beet_project }}"
beet_site_name: "Beetbox"

# Drupal settings.
drupal_create_makefile: yes
drupal_build_makefile: yes
drupal_install_site: yes
drupal_account_name: admin
drupal_account_pass: admin
php_memory_limit: "284M"

# Varnish config.
apache_listen_port: 8080
varnish_listen_port: 80
varnish_default_vcl_template_path: "{{ beet_base }}/.beetbox/templates/vcl.j2"

installed_extras:
  - adminer
  - mailhog
  - memcached
  - xdebug
  - xhprof
  - selenium
  - drupal-console
  - varnish
  # - pimpmylog
  # - nginx
  # - nodejs
  # - ruby
  # - solr
  # - redis

# Beetbox debug.
beet_debug: no
